### ISSUE TITLE
missing dependencies for qt with barrier

### ISSUE THREAD

**Issue by soubiliz** [pixlra/pixlra-gentoo-overlay#1]
`dev-qt/qtnetwork:5` is missing and so cmake fail when you try to build it. it's also a dependency of synergy 1 : https://gitweb.gentoo.org/repo/gentoo.git/tree/x11-misc/synergy/synergy-1.9.1.ebuild

**Comment by jfmcarreira** [comment]
Fixed by the above commits. Thanks for noticing.
